# Generated by Django 5.0.7 on 2025-07-13 12:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='technologies_used',
            field=models.JSONField(default=api.models.default_list),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='specifications',
            field=models.JSONField(blank=True, default=api.models.default_dict, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.JSONField(default=api.models.default_list),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tags',
            field=models.JSONField(default=api.models.default_list),
        ),
    ]
