# Generated by Django 5.0.7 on 2025-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_casestudy_technologies_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='company_logo',
            field=models.URLField(blank=True, help_text='URL to the company logo'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='image',
            field=models.URLField(blank=True, help_text='URL to the case study image'),
        ),
    ]
